import type { Metadata } from "next";
import { Geist, Geist_Mono, Ubuntu, IBM_Plex_Mono } from "next/font/google";
import '@/styles/global.scss';
import { Header } from "@/common/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  weight: ["400", "500", "700"], // выбери нужные веса
  subsets: ["latin"],
  variable: "--font-family",
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--second-family",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${ubuntu.variable} ${ibmPlexMono.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
